// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation CardExampleViewController
@end

@implementation MasterViewController
@end

@implementation CardExampleListCell
@end

@implementation CardExampleNotificationCell
@end

